logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    cc.coopersoft: WARN

camunda.bpm:
  database:
    schema-update: false
    type: mariadb
  webapp:
    index-redirect-enabled: true
  admin-user:
    id: camunda
    password: Cooper&camunda
  authorization:
    enabled: true
  filter:
    create: All tasks

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/construction/protocol/openid-connect/certs
  datasource:
    initialization-mode: NEVER
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    url: "jdbc:mysql://database:3306/camunda?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&nullDatabaseMeansCurrent=true&nullCatalogMeansCurrent=true"
    username: "root"
    password: "p0stgr@s"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    database: "MYSQL"
    show-sql: "false"
    hibernate:
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    properties:
      hibernate:
        ddl-auto: "none"
        enable_lazy_load_no_trans: true
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  cloud:
    consul:
      discovery:
        serviceName: ${spring.application.name}
        # 启用服务发现
        enabled: true
        # 启用服务注册
        register: true
        # 服务停止时取消注册
        deregister: true
        # 表示注册时使用IP而不是hostname
        prefer-ip-address: true
        # 执行监控检查的频率
        health-check-interval: 30s
        # 设置健康检查失败多长时间后，取消注册
        health-check-critical-timeout: 30s
        # 健康检查的路径
        health-check-path: /actuator/info
        # 服务注册标识，格式为：应用名称+服务器IP+端口
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    stream:
      rocketmq:
        binder:
          name-server:
            rmqnamesrv:9876
      bindings:
        fireCheckBusiness:
          destination: fireCheckBusinessTopic
          content-type: application/json

uid:
  timeBits: 30             # 时间位, 默认:30
  workerBits: 17           # 机器位, 默认:16
  seqBits: 6               # 序列号, 默认:7
  epochStr: "2019-09-01"   # 初始时间, 默认:"2019-02-20"
  enableBackward: true    # 是否容忍时钟回拨, 默认:true
  maxBackwardSeconds: 1    # 时钟回拨最长容忍时间（秒）, 默认:1
  CachedUidGenerator:     # CachedUidGenerator相关参数
    boostPower: 3          # RingBuffer size扩容参数, 可提高UID生成的吞吐量, 默认:3
    paddingFactor: 50      # 指定何时向RingBuffer中填充UID, 取值为百分比(0, 100), 默认为50
    #scheduleInterval: 60    # 默认:不配置此项, 即不实用Schedule线程. 如需使用, 请指定Schedule线程时间间隔, 单位:秒